/*
 *  This file was automatically generated by MoMEMta-MaGMEE,
 *  A MadGraph Matrix Element Exporter plugin for MoMEMta.
 *  
 *  It is subject to MoMEMta-MaGMEE's license and copyright:
 *  
 *  Copyright (C) 2016  Universite catholique de Louvain (UCL), Belgium
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <Parameters_%(model_name)s.h>

#include <SLHAReader.h>

namespace %(namespace)s_%(model_name)s {

    using namespace std;
    
    // Constructor
    Parameters_%(model_name)s::Parameters_%(model_name)s(const SLHA::Reader& card) {
    	// Prepare a vector for indices (for reading indexed entries)
    	vector<int> indices(2,0);
        
        %(parameter_map_lines)s

        this->cacheParameters();
        this->cacheCouplings();
    }  
    
    void Parameters_%(model_name)s::cacheParameters(){
    	// Define "zero"
    	zero=0;
    	ZERO=0;
    	%(set_independent_parameters)s
    }
    
    void Parameters_%(model_name)s::cacheCouplings(){
    	%(set_independent_couplings)s
    }
    
    void Parameters_%(model_name)s::updateParameters(){
    	%(set_dependent_parameters)s
    }
    
    void Parameters_%(model_name)s::updateCouplings(){
    	%(set_dependent_couplings)s
    }

}
